#!/bin/bash
#
# publish_ghost_blog ################################################
#                                                                   #
# Prepare and upload content for the "johnlane.ie" web site by      #
# extracting content from a Ghost blog hosted on this server.       #
# The web server's "private/bin/update" script updates the web site #
# with the uploaded content.                                        #
#                                                                   #
# A "~.netrc" file containing ftp credentials is required. It       #
# should be formatted like this:                                    #
#                                                                   #
#     machine <ftp-server> login <username> password <password>     #
#                                                                   #
# with <ftp-server>, <username> and <password> replaced by the      #
# actual values. The <ftp-server> value should equal the FTP_SERVER #
# setting below.                                                    #
#                                                                   #
# This script is indented to be executed regularly by cron.         #
#                                                                   #
#                                                        JL20131209 #
#                                                                   #
#####################################################################

# Required: see https://github.com/johnlane/random-toolbox/blob/master/usr/bin/ghostbuster
GHOSTBUSTER=/root/adm/gb2/ghostbuster
GHOST=/srv/ghost          # Extract and publish from Ghost installed at this path
#EXPORT=html_basic        # Exporter to use
EXPORT=html               # Exporter to use
FTP_SERVER="johnlane.ie"  # Upload published archive to this web server

# work in /tmp (write permission to create temporary files assumed)
cd /tmp

echo exporting published blog
tmpdir=$(mktemp -d) # export to temporary directory
"${GHOSTBUSTER}" "${GHOST}" $tmpdir --${EXPORT} --without-tags=private,Amylum --published -u http://johnlane.ie -v

if [[ $? == 0 ]]
then
    echo creating upload file
    tmpfile=$(mktemp ghostbuster-publish-$(date +%s)-XXXX)
    tar jcf $tmpfile -C $tmpdir .

    echo uploading to ${FTP_SERVER}
    ftp johnlane.ie <<- EOF
	cd private/uploads
	put $tmpfile
	EOF
else
    echo "An error occurred during export. Not uploaded"
fi

# clean up temporary files
rm -rf $tmpdir $tmpfile
